### ISSUE TITLE
Failed to run migration on testnet, it might due to some compilation inconsistencies

### ISSUE THREAD

**Issue by tranvictor** [ConsenSys/truffle#326]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle compile` compiled `migration` contract to have `lastCompletedMigration` instead of `last_completed_migration` and it led to this error:

```
/usr/local/lib/node_modules/truffle/lib/migrate.js:226
      migrations.last_completed_migration.call().then(function(completed_migration) {
                                         ^

TypeError: Cannot read property 'call' of undefined
    at /usr/local/lib/node_modules/truffle/lib/migrate.js:226:42
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/index.js:235:7
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
```
## Steps to Reproduce

I couldn't reproduce the bug on fresh project.

## Expected Behavior

The compiled migration file should have `last_completed_migration`
## Actual Results

It has `lastCompletedMigration` instead.
## Environment

* Operating System: MacOS
* Truffle version: v2.1.1

**Comment by tranvictor** [comment]
It turns out I used [zeppelin](http://zeppelin-solidity.readthedocs.io/en/latest/) to build up my contract and it has its own `migration` contract whose name exactly the same as `truffle`'s migration contract. Thus it is replaced by `zeppelin`'s one.

This is pretty tricky, I guess `truffle` should redesign the `build/contracts` directory structure so same name contracts don't replace each other.

**Comment by JGcarv** [comment]
Hi @tranvictor ! I'm facing the same issue. What did you do to solve it?
Thanks!

**Comment by tranvictor** [comment]
@JGcarv In my case, I just removed the redundant `migration` contract from zeppelin. See my comment above for better explanation 😄

**Comment by JGcarv** [comment]
I see. That makes sense. Thanks @tranvictor !

**Comment by tcoulter** [comment]
To clarify: Are all of you guys on Truffle 2? Truffle 3.x should fix this issue, as it has defined ordering of dependencies sources (i.e., your project first, then EthPM, then NPM). If you haven't yet, give Truffle 3.0 a try. It requires some upgrading, but you can find more information here: http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3

**Comment by tcoulter** [comment]
I'm going to close this ticket since it *should* be fix in Truffle 3. If Truffle 3 users still have this issue, please reopen.

**Comment by interfect** [comment]
I can confirm that this issue persists in Truffle v3.2.7, and has screwed up my live net deployment. The Zeppelin Migrations contract, which I don't use, gets built and clobbers the Truffle Migrations contract.

The two are *just* similar enough that migrations can run, if the migrations contract has not yet been deployed, but then subsequent attempts to run migrations fail with the incredibly uninformative:

```
$ truffle migrate
Using network 'development'.

TypeError: Cannot read property 'call' of undefined
    at <snip>\npm\node_modules\truffle\build\cli.bundled.js:54937:49
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Truffle should fail at the compile step if two contracts have the same name, because it can't do anything other than clobber one with the other.

Alternately, "Truffle" should be sprinkled liberally throughout the migrations contract method names, to avoid giving the appearance of working when you have the wrong contract.

**Comment by berlinguyinca** [comment]
I'm seeing the same issue here

**Comment by Ethbet** [comment]
We were having this issue as well, it was temporarily fixed by removing all built contracts from their directory. There still appear to be several bugs in this catagory in the latest version of truffle regardless.

**Comment by tmm360** [comment]
This should be reopened because is still an active issue. @tranvictor @tcoulter

**Comment by tmm360** [comment]
Sorry, my fault... I've updated my code and appear to be solved. Will update if it isn't.

**Comment by Kuzirashi** [comment]
```
➜  git:(master) ✗ truffle version  
truTruffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
➜   git:(master) ✗ truffle migrate --network test
Using network 'test'.

TypeError: Cannot read property 'call' of undefined
    at /home/kuzi/.nvm/versions/node/v9.2.0/lib/node_modules/truffle/build/cli.bundled.js:175527:50
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
➜  git:(master) ✗ 
```

Very unhelpful error messages. Hard to debug. : /

**Comment by louisgv** [comment]
I stumbled upon the same problem while trying to run `truffle migrate`. All I had to do was to simply remove the `build` directory, restart Ganache, and `truffle migrate` runs smooth afterward.

```
truffle version
Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)
```

**Comment by JackPickering** [comment]
I am having this same issue with the error that @tranvictor got at the start, at the exact same line however, my contracts folder does not contain an additional migrations file (i.e. I just have the one), yet I still get the error at the module:
`  lastCompletedMigration: function(options, callback) {
    var Migrations;

    try {
      Migrations = options.resolver.require("Migrations");
    } catch (e) {
      return callback(new Error("Could not find built Migrations contract: " + e.message));
    }

    if (Migrations.isDeployed() == false) {
      return callback(null, 0);
    }

    var migrations = Migrations.deployed();

    Migrations.deployed().then(function(migrations) {
      return migrations.last_completed_migration.call();
    }).then(function(completed_migration) {
      callback(null, completed_migration.toNumber());
    }).catch(callback);
  },`

The line that throws is:
`   return migrations.last_completed_migration.call();`

Meaning the method last_completed_migration is not being found. Where would this be? Is there a way of altering the migrations folder to specifically call this instead?

This is absolutely vital to be able to deploy large sets of contracts which are inter-linked as you cannot expect people to risk spending $100 on every migration to deploy them all together and as it stands, you cannot migrate contracts separately using truffle due to this error.

**Comment by JackPickering** [comment]
I've updated to Truffle @4.1.3

This is my migrations.sol contract...
```
pragma solidity ^0.4.17;

contract Migrations {
  address public owner;
  uint public last_completed_migration;

  modifier restricted() {
    if (msg.sender == owner) _;
  }

  function Migrations() public {
    owner = msg.sender;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
```

This is my migrations.js file...

```
var Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer) {
  deployer.deploy(Migrations);
};
```

Where is this new logic meant to be?

**Comment by cgewecke** [comment]
@JackPickering The new logic is at `truffle-migrate` where the migrations are processed. There are now two possible versions of the standard migrations contract - the original and a newer one that follows the Solidity style guidelines and camel cases the variable names. It's installed when anyone starts a new project from scratch with `truffle init`.

The ABI you showed indicates the compiled contract you're interacting with is the newer version:
```
{ "constant": true, "inputs": [], "name": "lastCompletedMigration", "outputs": [ { "name": "", "type": "uint256" } ],
```

Is Petshop the project you're working on?

**Comment by JackPickering** [comment]
Okay, that makes sense thank you, its worked but now I get a different error unrelated to this thread. Myabe you could help though if you wouldnt mind? It basically now says `Error: Could not set `null` as the transaction hash for SaleStagesLib` when I try to link a library that has already been migrated. 
https://github.com/trufflesuite/truffle-migrate/issues/24

Much appreciated, 
Thanks
